### ISSUE TITLE
Sample Code not found

### ISSUE THREAD

**Issue by wang-chi** [MicrosoftDocs/xamarin-docs.zh-tw#24]
This solution provide sample code not found~

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 3e6b1679-7d43-32c2-0ea9-72c2bda2da06
* Version Independent ID: 63828f35-0a1e-1613-bc7f-4f8d95ac3fe7
* Content: [非同步支援概觀 - Xamarin](https://docs.microsoft.com/zh-tw/xamarin/cross-platform/platform/async)
* Content Source: [docs/cross-platform/platform/async.md](https://github.com/MicrosoftDocs/xamarin-docs.zh-TW/blob/live/docs/cross-platform/platform/async.md)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by lichasu** [comment]
Hello, @wang-chi 
 
We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment? Where is the code missing? The localized page has the same ones as the source.
 
Kind regards,
Microsoft DOCS International Team

**Comment by wang-chi** [comment]
Sorry, I comment the wrong page.
The true page is also comment (https://github.com/MicrosoftDocs/xamarin-docs.zh-tw/issues/25).

**Comment by CeciAc** [comment]
Hello, @wang-chi 

Your contribution is much appreciated. Our team reviewed your feedback and it appears that this issue has been already logged.
Please review issue #25  For this reason we are closing this issue since it is duplicated.

Kind regards,
Microsoft DOCS International Team
